### ISSUE TITLE
Not Sync db from QT version: tyzen-23.100.0-win64 

### ISSUE THREAD

**Issue by vanthoi** [tyzen-tzn/tyzen#4]
Unable to complete synchronization from scratch. Arriving at block close to 5000 rejected.
Unable to update db from version 1.0.0.1 to version tyzen-23.100.0

**Comment by MonkeyD-Core** [comment]
You have to compile from the source code if you want to use V23.100 , or wait i release the new compiled version. it may will be released in 2 days for windows and linux
